### ISSUE TITLE
Ethstats doesn't work

### ISSUE THREAD

**Issue by deniztoprak** [MaibornWolff/eden#15]
Ethstats-monitor in `geth-poa-docker` runs into a problem on startup and it doesn't work properly. The log file outputs:

`tail: unrecognized file system type 0x794c7630 for '/home/ethnetintel/.pm2/logs/node-app-out-0.log'`

**Comment by deniztoprak** [comment]
Same problem on `parity-poa-docker`.

**Comment by marsmensch** [comment]
I would prefer to fix the issue in a different way long term. ethstats is not well maintained anymore. Eg Blockscout is a great alternative and well suited for PoA ETH deployments https://github.com/poanetwork/blockscout

your opinion on this @froid1911 ?

**Comment by deniztoprak** [comment]
@marsmensch @froid1911 I tried to integrate blockscout as a block explorer but it didn't work quite well. The [build process](https://github.com/poanetwork/blockscout/tree/master/docker) is somehow messy, you have to execute `Makefile` that builds a docker image and runs it. When we do the process inside a container, we run a container internally in another, which is an [anti-pattern](https://stackoverflow.com/a/33003273/728162). There is a pending [pull request](https://github.com/poanetwork/blockscout/pull/1703) to implement docker-compose without the make script. I suggest to wait a while until it gets merged.

**Comment by deniztoprak** [comment]
I can't reproduce anymore the initial problem with Ethstats-monitor. It was probably due to a corrupt docker image, after running `docker system prune` and `docker network prune` the error is gone. So I close this issue.
